### ISSUE TITLE
Beamformers

### ISSUE THREAD

**Issue by Toplica001** [fakufaku/torchiva#5]
Hello, how to use beamformers (which script do i need to run and how?) and are beamformers AI based or not? And one more thing, on one pc i can install this library but on my main pc i can't, when i try to install it says that i dont have module named fcntl which is the module related to linux. Do u have a solution for that as well or not, on one windows pc works on the other doesn't? Thank you in advance.

**Comment by fakufaku** [comment]
Hi @Toplica001 , sorry there are no example code for the beamformers, but you could try to modify the training code in the examples folder.
The beamformers are hybrid with the target/noise statistics being estimated with a NN and the beamformers are computing according to some traditional optimal formulation.

I don't know about the fcntl module. This is not a direct dependency of torchiva (probably a dependency of a dependency) so I cannot help you here. The main dependency is pytorch, so if you can install it, you should be able to use the separation modules I think.

**Comment by Toplica001** [comment]
Ok, thank you for your reply.
