### ISSUE TITLE
Trained model 

### ISSUE THREAD

**Issue by aleksandra-bebe** [fakufaku/torchiva#6]
Hello, does this trained model work just with tiss or  can work with mvdr and others beamformers?

**Comment by fakufaku** [comment]
Hi, I haven't tried, but I think it would work just with tiss.

**Comment by aleksandra-bebe** [comment]
Thank you for answer, yes it only works with tiss, and just one more question is script test_beamformers use model or is that just to see if the beamformers work and if we want to train models for beamformers should the dataset you specified for training need to be paid for?

**Comment by fakufaku** [comment]
test_beamformers.py is just a coffee correctness test and does not use a trained model. But you could use it as a reference on how to use the code.

The dataset we used was based on WSJ0, which is paid. The noise part is from Chime3 challenge and I believe it's free.
You could replace the speech by that of librimix for example if you need something free. It's structure is similar to WSJ0, so should require minimal code change.

**Comment by aleksandra-bebe** [comment]
Thank you very much.
